### PR TITLE
[RFC] sysconfig/kdump: change KDUMP_CPU default value to 0

### PR DESCRIPTION
**Pull request by sourabhjains**
By default, use all available CPUs to collect the dump instead of just one CPU. This reduces the dump collection time significantly, specially for the systems with very large memory configuration.

The graph below show the time reduction in dump collection on large memory system from 4 Hours to 10 Minutes.

                               |
                       14000   | *
                               |
                               |
                               |
                               |
                               |
                               |
                        1600   |      *
                               |
                               |
                        1400   |
 execution Time (Sec)          |
                               |
                        1200   |
                               |
                               |
                        1000   |
                               |            *
                               |
                        800    |
                               |
                               |                   *
                        600    |
                               |                          *     *
                               |
                                ------------------------------------
                                   1    9    17    25     33    41

                                          Number of Threads

System details:
Architecture: PowerPC
/proc/vmcore size: 3.7T
Filter level: 1

Similar tests with different filter levels, 31 and 16, also show significant reduction in time consumption for dump collection.

Although the above tests were performed only on the PowerPC architecture, but I think using all CPUs for dump collection will have performance benefits on other architectures too.

### CODE REVIEW

**Comment by ptesarik** [comment]
Yes, the default of `KDUMP_CPU=1` dates back to times where SMP boot after crash kexec was unstable. It probably should have been changed years ago.

Note that a similar change is most likely also needed in [yast-kdump](https://github.com/yast/yast-kdump).

**Comment by ptesarik** [comment]
@sourabhjains Would you mind actually changing the default value in code if no value is set? This is `build_kdump_commandline()` [here](https://github.com/openSUSE/kdump/blob/5784fc6ec1134ff67624112db5d7e43996d81b8f/init/load.sh#L99) in `init/load.sh`.

**Comment by ptesarik** [comment]
Please, also update the [man page](https://github.com/openSUSE/kdump/blob/5784fc6ec1134ff67624112db5d7e43996d81b8f/doc/man/kdump.5.txt.in#L86).

**Comment by sourabhjains** [comment]
> Yes, the default of `KDUMP_CPUS=1` dates back to times where SMP boot after crash kexec was unstable. It probably should have been changed years ago.
> 

 Good to know you liked the idea.

> Note that a similar change is most likely also needed in [yast-kdump](https://github.com/yast/yast-kdump).

Sure, I will update the yast-kdump as well.

**Comment by sourabhjains** [comment]
> @sourabhjains Would you mind actually changing the default value in code if no value is set? This is `build_kdump_commandline()` [here](https://github.com/openSUSE/kdump/blob/5784fc6ec1134ff67624112db5d7e43996d81b8f/init/load.sh#L99) in `init/load.sh`.
> 
> EDIT: Or is it now in `kdump-read-config.sh` [here](https://github.com/openSUSE/kdump/blob/5784fc6ec1134ff67624112db5d7e43996d81b8f/kdump-read-config.sh#L13), @jiribohac?

@ptesarik I will ensure that if no value or an invalid value is set in the KDUMP_CPU config, the kdump-save script uses all available CPUs.

I will also update the man page.

Thanks for the review @ptesarik.

**Comment by sourabhjains** [comment]
Thanks @jiribohac for accepting the patch.

**Pull request merged**
